#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"

# Remove files generated by the pipeline while preserving event inputs.
rm -f \
    "$SCRIPT_DIR/database.h5" \
    "$SCRIPT_DIR/output.h5" \
    "$SCRIPT_DIR/result.toml" \
    "$SCRIPT_DIR/report.md" \
    "$SCRIPT_DIR/driver.log" \
    "$SCRIPT_DIR/input.log" \
    "$SCRIPT_DIR/preprocess.log" \
    "$SCRIPT_DIR/output.log" \
    "$SCRIPT_DIR/report.log" \
    "$SCRIPT_DIR/.decision.txt"

rm -rf "$SCRIPT_DIR/status"
rm -rf "$SCRIPT_DIR/figures"

echo "Removed event1 pipeline outputs."
